# All available hooks: https://pre-commit.com/hooks.html
repos:
- repo: https://github.com/jolars/panache-pre-commit
  rev: v3.12.0
  hooks:
    # Format Markdown, Quarto, and RMarkdown files
    - id: panache-format
    # Lint files and auto-fix issues
    - id: panache-lint
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=200']
    - id: check-yaml
